### ISSUE TITLE
Implement `cumtrapz`

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/libtopotoolbox#144]
This function computes the integral of a quantity along a stream network using a trapezoidal integration formula. This is a relatively straightforward graph traversal.

**Comment by wschwanghart** [comment]
This is a good idea. In fact, cumtrapz in upstream direction can be used for various purposes. For example, to calculate distances from the outlet, cumtrapz would just require integrating over a vector of ones. For calculating labels for drainage basins, cumtrapz would require a vector with labels (some unique integer values) at the outlets, and zeros elsewhere. As such, cumtrapz could be used quite generically. Given its generic purpose, we should aim to implement it that it takes different data formats (e.g. single and double).
