### ISSUE TITLE
Sink filling (`fillsinks`)

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/libtopotoolbox#7]
The MATLAB code uses [morphological reconstruction](https://doi.org/10.1109/83.217222) as implemented by the Image Processing Toolbox ([`imreconstruct`](https://www.mathworks.com/help/images/ref/imreconstruct.html)) to fill sinks in the DEM.

@Teschl: you have some sink filling C code, right? How confident are you that it works?

**Comment by Teschl** [comment]
The fillsinks code only fills sinks that are 1 pixel in size. So as of right now i would say it does not work at all.

**Comment by wschwanghart** [comment]
Yes, filling sinks is not trivial...

**Comment by wkearn** [comment]
I have something that replicates the MATLAB `imreconstruct` functionality in C. I'll try to get a pull request together today so we can have a look. Even if we ultimately decide to implement sink filling in a different way, I think it will be a good point to start iterating on the library interface and to start building some frameworks for testing, benchmarking and documentation.

**Comment by wschwanghart** [comment]
A replication of `imreconstruct` would be perfect as morphological image reconstruction is much more flexible than most sink-filling algorithms. For example, it is relatively straight forward to fill only smaller sinks (see the `fillsinks` function). This is important for handling endorheic basins, for example.
